/*
 * Paubox Email API
 * Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.paubox.api;

import com.paubox.ApiException;
import com.paubox.model.DeleteDynamicTemplate200Response;
import com.paubox.model.DynamicTemplateListResponse;
import com.paubox.model.DynamicTemplateResponse;
import com.paubox.model.ErrorResponse;
import java.io.File;
import com.paubox.model.SingleSendResponse;
import com.paubox.model.TemplatedMessageRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for DynamicTemplatesApi
 */
@Disabled
public class DynamicTemplatesApiTest {

    private final DynamicTemplatesApi api = new DynamicTemplatesApi();

    
    /**
     * Create a dynamic template
     *
     * Upload a new Handlebars template for dynamic content generation
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createDynamicTemplateTest() throws ApiException {
        String dataName = null;
        File dataBody = null;
        DynamicTemplateResponse response = 
        api.createDynamicTemplate(dataName, dataBody);
        
        // TODO: test validations
    }
    
    /**
     * Delete a dynamic template
     *
     * Delete a specific dynamic template by ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteDynamicTemplateTest() throws ApiException {
        String id = null;
        DeleteDynamicTemplate200Response response = 
        api.deleteDynamicTemplate(id);
        
        // TODO: test validations
    }
    
    /**
     * Get a dynamic template
     *
     * Retrieve a specific dynamic template by ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDynamicTemplateTest() throws ApiException {
        String id = null;
        DynamicTemplateResponse response = 
        api.getDynamicTemplate(id);
        
        // TODO: test validations
    }
    
    /**
     * List all dynamic templates
     *
     * Retrieve all dynamic templates for your organization
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listDynamicTemplatesTest() throws ApiException {
        DynamicTemplateListResponse response = 
        api.listDynamicTemplates();
        
        // TODO: test validations
    }
    
    /**
     * Send a dynamically templated message
     *
     * Send an email using a dynamic template with variable substitution
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendTemplatedMessageTest() throws ApiException {
        TemplatedMessageRequest templatedMessageRequest = null;
        SingleSendResponse response = 
        api.sendTemplatedMessage(templatedMessageRequest);
        
        // TODO: test validations
    }
    
    /**
     * Update a dynamic template
     *
     * Update an existing Handlebars template
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateDynamicTemplateTest() throws ApiException {
        String id = null;
        String dataName = null;
        File dataBody = null;
        DynamicTemplateResponse response = 
        api.updateDynamicTemplate(id, dataName, dataBody);
        
        // TODO: test validations
    }
    
}
