/*
 * Paubox Email API
 * Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.paubox.api;

import com.paubox.ApiException;
import com.paubox.model.BulkSendRequest;
import com.paubox.model.BulkSendResponse;
import com.paubox.model.ErrorResponse;
import com.paubox.model.MessageReceiptErrorResponse;
import com.paubox.model.MessageReceiptResponse;
import com.paubox.model.SingleSendRequest;
import com.paubox.model.SingleSendResponse;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for MessagesApi
 */
@Disabled
public class MessagesApiTest {

    private final MessagesApi api = new MessagesApi();

    
    /**
     * Get email disposition
     *
     * Retrieve delivery status, open tracking, and click tracking information for a sent message
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMessageReceiptTest() throws ApiException {
        UUID sourceTrackingId = null;
        MessageReceiptResponse response = 
        api.getMessageReceipt(sourceTrackingId);
        
        // TODO: test validations
    }
    
    /**
     * Send multiple email messages (batch)
     *
     * Sends multiple messages in one request. Paubox recommends batches of 50 or fewer. Source tracking IDs are returned in the same order as the messages array. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendBulkMessagesTest() throws ApiException {
        BulkSendRequest bulkSendRequest = null;
        BulkSendResponse response = 
        api.sendBulkMessages(bulkSendRequest);
        
        // TODO: test validations
    }
    
    /**
     * Send a single email message
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendMessageTest() throws ApiException {
        SingleSendRequest singleSendRequest = null;
        SingleSendResponse response = 
        api.sendMessage(singleSendRequest);
        
        // TODO: test validations
    }
    
}
