/*
 * Paubox Email API
 * Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.paubox.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DeliveryStatus
 */
class DeliveryStatusTest {
    private final DeliveryStatus model = new DeliveryStatus();

    /**
     * Model tests for DeliveryStatus
     */
    @Test
    void testDeliveryStatus() {
        // TODO: test DeliveryStatus
    }

    /**
     * Test the property 'deliveryStatus'
     */
    @Test
    void deliveryStatusTest() {
        // TODO: test deliveryStatus
    }

    /**
     * Test the property 'deliveryTime'
     */
    @Test
    void deliveryTimeTest() {
        // TODO: test deliveryTime
    }

    /**
     * Test the property 'openedStatus'
     */
    @Test
    void openedStatusTest() {
        // TODO: test openedStatus
    }

    /**
     * Test the property 'openedTime'
     */
    @Test
    void openedTimeTest() {
        // TODO: test openedTime
    }

}
