/*
 * Paubox Email API
 * Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.paubox.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.paubox.model.ClickData;
import com.paubox.model.MessageDelivery;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MessageReceiptResponseDataMessage
 */
class MessageReceiptResponseDataMessageTest {
    private final MessageReceiptResponseDataMessage model = new MessageReceiptResponseDataMessage();

    /**
     * Model tests for MessageReceiptResponseDataMessage
     */
    @Test
    void testMessageReceiptResponseDataMessage() {
        // TODO: test MessageReceiptResponseDataMessage
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'messageDeliveries'
     */
    @Test
    void messageDeliveriesTest() {
        // TODO: test messageDeliveries
    }

    /**
     * Test the property 'totalOpens'
     */
    @Test
    void totalOpensTest() {
        // TODO: test totalOpens
    }

    /**
     * Test the property 'distinctOpens'
     */
    @Test
    void distinctOpensTest() {
        // TODO: test distinctOpens
    }

    /**
     * Test the property 'totalClickCount'
     */
    @Test
    void totalClickCountTest() {
        // TODO: test totalClickCount
    }

    /**
     * Test the property 'clicksPerLink'
     */
    @Test
    void clicksPerLinkTest() {
        // TODO: test clicksPerLink
    }

    /**
     * Test the property 'unsubscribed'
     */
    @Test
    void unsubscribedTest() {
        // TODO: test unsubscribed
    }

}
