/*
 * Paubox Email API
 * Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.paubox.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.paubox.model.Attachment;
import com.paubox.model.TemplatedMessageHeaders;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TemplatedMessage
 */
class TemplatedMessageTest {
    private final TemplatedMessage model = new TemplatedMessage();

    /**
     * Model tests for TemplatedMessage
     */
    @Test
    void testTemplatedMessage() {
        // TODO: test TemplatedMessage
    }

    /**
     * Test the property 'recipients'
     */
    @Test
    void recipientsTest() {
        // TODO: test recipients
    }

    /**
     * Test the property 'bcc'
     */
    @Test
    void bccTest() {
        // TODO: test bcc
    }

    /**
     * Test the property 'cc'
     */
    @Test
    void ccTest() {
        // TODO: test cc
    }

    /**
     * Test the property 'headers'
     */
    @Test
    void headersTest() {
        // TODO: test headers
    }

    /**
     * Test the property 'allowNonTLS'
     */
    @Test
    void allowNonTLSTest() {
        // TODO: test allowNonTLS
    }

    /**
     * Test the property 'forceSecureNotification'
     */
    @Test
    void forceSecureNotificationTest() {
        // TODO: test forceSecureNotification
    }

    /**
     * Test the property 'attachments'
     */
    @Test
    void attachmentsTest() {
        // TODO: test attachments
    }

}
