/*
 * Paubox Email API
 * Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.paubox;

import java.util.HashSet;

/**
 * Representing a Server Variable for server URL template substitution.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-09T17:40:55.003620791Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class ServerVariable {
    public String description;
    public String defaultValue;
    public HashSet<String> enumValues = null;

    /**
     * @param description A description for the server variable.
     * @param defaultValue The default value to use for substitution.
     * @param enumValues An enumeration of string values to be used if the substitution options are from a limited set.
     */
    public ServerVariable(String description, String defaultValue, HashSet<String> enumValues) {
        this.description = description;
        this.defaultValue = defaultValue;
        this.enumValues = enumValues;
    }
}
