/*
 * Paubox Email API
 * Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.paubox.api;

import com.paubox.ApiClient;
import com.paubox.ApiException;
import com.paubox.ApiResponse;
import com.paubox.Configuration;
import com.paubox.Pair;

import com.paubox.model.DeleteDynamicTemplate200Response;
import com.paubox.model.DynamicTemplateListResponse;
import com.paubox.model.DynamicTemplateResponse;
import com.paubox.model.ErrorResponse;
import java.io.File;
import com.paubox.model.SingleSendResponse;
import com.paubox.model.TemplatedMessageRequest;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import org.apache.http.HttpEntity;
import org.apache.http.NameValuePair;
import org.apache.http.entity.mime.MultipartEntityBuilder;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.client.entity.UrlEncodedFormEntity;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-09T17:40:55.003620791Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class DynamicTemplatesApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public DynamicTemplatesApi() {
    this(Configuration.getDefaultApiClient());
  }

  public DynamicTemplatesApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Create a dynamic template
   * Upload a new Handlebars template for dynamic content generation
   * @param dataName Name for the template (required)
   * @param dataBody Handlebars template file (.hbs) (required)
   * @return DynamicTemplateResponse
   * @throws ApiException if fails to make API call
   */
  public DynamicTemplateResponse createDynamicTemplate(@javax.annotation.Nonnull String dataName, @javax.annotation.Nonnull File dataBody) throws ApiException {
    return createDynamicTemplate(dataName, dataBody, null);
  }

  /**
   * Create a dynamic template
   * Upload a new Handlebars template for dynamic content generation
   * @param dataName Name for the template (required)
   * @param dataBody Handlebars template file (.hbs) (required)
   * @param headers Optional headers to include in the request
   * @return DynamicTemplateResponse
   * @throws ApiException if fails to make API call
   */
  public DynamicTemplateResponse createDynamicTemplate(@javax.annotation.Nonnull String dataName, @javax.annotation.Nonnull File dataBody, Map<String, String> headers) throws ApiException {
    ApiResponse<DynamicTemplateResponse> localVarResponse = createDynamicTemplateWithHttpInfo(dataName, dataBody, headers);
    return localVarResponse.getData();
  }

  /**
   * Create a dynamic template
   * Upload a new Handlebars template for dynamic content generation
   * @param dataName Name for the template (required)
   * @param dataBody Handlebars template file (.hbs) (required)
   * @return ApiResponse&lt;DynamicTemplateResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DynamicTemplateResponse> createDynamicTemplateWithHttpInfo(@javax.annotation.Nonnull String dataName, @javax.annotation.Nonnull File dataBody) throws ApiException {
    return createDynamicTemplateWithHttpInfo(dataName, dataBody, null);
  }

  /**
   * Create a dynamic template
   * Upload a new Handlebars template for dynamic content generation
   * @param dataName Name for the template (required)
   * @param dataBody Handlebars template file (.hbs) (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;DynamicTemplateResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DynamicTemplateResponse> createDynamicTemplateWithHttpInfo(@javax.annotation.Nonnull String dataName, @javax.annotation.Nonnull File dataBody, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createDynamicTemplateRequestBuilder(dataName, dataBody, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createDynamicTemplate", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<DynamicTemplateResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        DynamicTemplateResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<DynamicTemplateResponse>() {});
        

        return new ApiResponse<DynamicTemplateResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createDynamicTemplateRequestBuilder(@javax.annotation.Nonnull String dataName, @javax.annotation.Nonnull File dataBody, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'dataName' is set
    if (dataName == null) {
      throw new ApiException(400, "Missing the required parameter 'dataName' when calling createDynamicTemplate");
    }
    // verify the required parameter 'dataBody' is set
    if (dataBody == null) {
      throw new ApiException(400, "Missing the required parameter 'dataBody' when calling createDynamicTemplate");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/dynamic_templates";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    MultipartEntityBuilder multiPartBuilder = MultipartEntityBuilder.create();
    boolean hasFiles = false;
    if (dataName != null) {
        multiPartBuilder.addTextBody("data[name]", dataName.toString());
    }
    multiPartBuilder.addBinaryBody("data[body]", dataBody);
    hasFiles = true;
    HttpEntity entity = multiPartBuilder.build();
    HttpRequest.BodyPublisher formDataPublisher;
    if (hasFiles) {
        Pipe pipe;
        try {
            pipe = Pipe.open();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        new Thread(() -> {
            try (OutputStream outputStream = Channels.newOutputStream(pipe.sink())) {
                entity.writeTo(outputStream);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }).start();
        formDataPublisher = HttpRequest.BodyPublishers.ofInputStream(() -> Channels.newInputStream(pipe.source()));
    } else {
        ByteArrayOutputStream formOutputStream = new ByteArrayOutputStream();
        try {
            entity.writeTo(formOutputStream);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        byte[] formBytes = formOutputStream.toByteArray();
        formDataPublisher = HttpRequest.BodyPublishers
            .ofInputStream(() -> new ByteArrayInputStream(formBytes));
    }
    localVarRequestBuilder
        .header("Content-Type", entity.getContentType().getValue())
        .method("POST", formDataPublisher);
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete a dynamic template
   * Delete a specific dynamic template by ID
   * @param id Template ID to delete (required)
   * @return DeleteDynamicTemplate200Response
   * @throws ApiException if fails to make API call
   */
  public DeleteDynamicTemplate200Response deleteDynamicTemplate(@javax.annotation.Nonnull String id) throws ApiException {
    return deleteDynamicTemplate(id, null);
  }

  /**
   * Delete a dynamic template
   * Delete a specific dynamic template by ID
   * @param id Template ID to delete (required)
   * @param headers Optional headers to include in the request
   * @return DeleteDynamicTemplate200Response
   * @throws ApiException if fails to make API call
   */
  public DeleteDynamicTemplate200Response deleteDynamicTemplate(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    ApiResponse<DeleteDynamicTemplate200Response> localVarResponse = deleteDynamicTemplateWithHttpInfo(id, headers);
    return localVarResponse.getData();
  }

  /**
   * Delete a dynamic template
   * Delete a specific dynamic template by ID
   * @param id Template ID to delete (required)
   * @return ApiResponse&lt;DeleteDynamicTemplate200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DeleteDynamicTemplate200Response> deleteDynamicTemplateWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
    return deleteDynamicTemplateWithHttpInfo(id, null);
  }

  /**
   * Delete a dynamic template
   * Delete a specific dynamic template by ID
   * @param id Template ID to delete (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;DeleteDynamicTemplate200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DeleteDynamicTemplate200Response> deleteDynamicTemplateWithHttpInfo(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteDynamicTemplateRequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteDynamicTemplate", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<DeleteDynamicTemplate200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        DeleteDynamicTemplate200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<DeleteDynamicTemplate200Response>() {});
        

        return new ApiResponse<DeleteDynamicTemplate200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteDynamicTemplateRequestBuilder(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling deleteDynamicTemplate");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/dynamic_templates/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get a dynamic template
   * Retrieve a specific dynamic template by ID
   * @param id Template ID (required)
   * @return DynamicTemplateResponse
   * @throws ApiException if fails to make API call
   */
  public DynamicTemplateResponse getDynamicTemplate(@javax.annotation.Nonnull String id) throws ApiException {
    return getDynamicTemplate(id, null);
  }

  /**
   * Get a dynamic template
   * Retrieve a specific dynamic template by ID
   * @param id Template ID (required)
   * @param headers Optional headers to include in the request
   * @return DynamicTemplateResponse
   * @throws ApiException if fails to make API call
   */
  public DynamicTemplateResponse getDynamicTemplate(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    ApiResponse<DynamicTemplateResponse> localVarResponse = getDynamicTemplateWithHttpInfo(id, headers);
    return localVarResponse.getData();
  }

  /**
   * Get a dynamic template
   * Retrieve a specific dynamic template by ID
   * @param id Template ID (required)
   * @return ApiResponse&lt;DynamicTemplateResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DynamicTemplateResponse> getDynamicTemplateWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
    return getDynamicTemplateWithHttpInfo(id, null);
  }

  /**
   * Get a dynamic template
   * Retrieve a specific dynamic template by ID
   * @param id Template ID (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;DynamicTemplateResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DynamicTemplateResponse> getDynamicTemplateWithHttpInfo(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getDynamicTemplateRequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getDynamicTemplate", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<DynamicTemplateResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        DynamicTemplateResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<DynamicTemplateResponse>() {});
        

        return new ApiResponse<DynamicTemplateResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getDynamicTemplateRequestBuilder(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getDynamicTemplate");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/dynamic_templates/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List all dynamic templates
   * Retrieve all dynamic templates for your organization
   * @return DynamicTemplateListResponse
   * @throws ApiException if fails to make API call
   */
  public DynamicTemplateListResponse listDynamicTemplates() throws ApiException {
    return listDynamicTemplates(null);
  }

  /**
   * List all dynamic templates
   * Retrieve all dynamic templates for your organization
   * @param headers Optional headers to include in the request
   * @return DynamicTemplateListResponse
   * @throws ApiException if fails to make API call
   */
  public DynamicTemplateListResponse listDynamicTemplates(Map<String, String> headers) throws ApiException {
    ApiResponse<DynamicTemplateListResponse> localVarResponse = listDynamicTemplatesWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * List all dynamic templates
   * Retrieve all dynamic templates for your organization
   * @return ApiResponse&lt;DynamicTemplateListResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DynamicTemplateListResponse> listDynamicTemplatesWithHttpInfo() throws ApiException {
    return listDynamicTemplatesWithHttpInfo(null);
  }

  /**
   * List all dynamic templates
   * Retrieve all dynamic templates for your organization
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;DynamicTemplateListResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DynamicTemplateListResponse> listDynamicTemplatesWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listDynamicTemplatesRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listDynamicTemplates", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<DynamicTemplateListResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        DynamicTemplateListResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<DynamicTemplateListResponse>() {});
        

        return new ApiResponse<DynamicTemplateListResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listDynamicTemplatesRequestBuilder(Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/dynamic_templates";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Send a dynamically templated message
   * Send an email using a dynamic template with variable substitution
   * @param templatedMessageRequest  (required)
   * @return SingleSendResponse
   * @throws ApiException if fails to make API call
   */
  public SingleSendResponse sendTemplatedMessage(@javax.annotation.Nonnull TemplatedMessageRequest templatedMessageRequest) throws ApiException {
    return sendTemplatedMessage(templatedMessageRequest, null);
  }

  /**
   * Send a dynamically templated message
   * Send an email using a dynamic template with variable substitution
   * @param templatedMessageRequest  (required)
   * @param headers Optional headers to include in the request
   * @return SingleSendResponse
   * @throws ApiException if fails to make API call
   */
  public SingleSendResponse sendTemplatedMessage(@javax.annotation.Nonnull TemplatedMessageRequest templatedMessageRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<SingleSendResponse> localVarResponse = sendTemplatedMessageWithHttpInfo(templatedMessageRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Send a dynamically templated message
   * Send an email using a dynamic template with variable substitution
   * @param templatedMessageRequest  (required)
   * @return ApiResponse&lt;SingleSendResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<SingleSendResponse> sendTemplatedMessageWithHttpInfo(@javax.annotation.Nonnull TemplatedMessageRequest templatedMessageRequest) throws ApiException {
    return sendTemplatedMessageWithHttpInfo(templatedMessageRequest, null);
  }

  /**
   * Send a dynamically templated message
   * Send an email using a dynamic template with variable substitution
   * @param templatedMessageRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;SingleSendResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<SingleSendResponse> sendTemplatedMessageWithHttpInfo(@javax.annotation.Nonnull TemplatedMessageRequest templatedMessageRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = sendTemplatedMessageRequestBuilder(templatedMessageRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("sendTemplatedMessage", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<SingleSendResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        SingleSendResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<SingleSendResponse>() {});
        

        return new ApiResponse<SingleSendResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder sendTemplatedMessageRequestBuilder(@javax.annotation.Nonnull TemplatedMessageRequest templatedMessageRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'templatedMessageRequest' is set
    if (templatedMessageRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'templatedMessageRequest' when calling sendTemplatedMessage");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/templated_messages";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(templatedMessageRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Update a dynamic template
   * Update an existing Handlebars template
   * @param id Template ID to update (required)
   * @param dataName Updated name for the template (optional)
   * @param dataBody Updated Handlebars template file (.hbs) (optional)
   * @return DynamicTemplateResponse
   * @throws ApiException if fails to make API call
   */
  public DynamicTemplateResponse updateDynamicTemplate(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String dataName, @javax.annotation.Nullable File dataBody) throws ApiException {
    return updateDynamicTemplate(id, dataName, dataBody, null);
  }

  /**
   * Update a dynamic template
   * Update an existing Handlebars template
   * @param id Template ID to update (required)
   * @param dataName Updated name for the template (optional)
   * @param dataBody Updated Handlebars template file (.hbs) (optional)
   * @param headers Optional headers to include in the request
   * @return DynamicTemplateResponse
   * @throws ApiException if fails to make API call
   */
  public DynamicTemplateResponse updateDynamicTemplate(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String dataName, @javax.annotation.Nullable File dataBody, Map<String, String> headers) throws ApiException {
    ApiResponse<DynamicTemplateResponse> localVarResponse = updateDynamicTemplateWithHttpInfo(id, dataName, dataBody, headers);
    return localVarResponse.getData();
  }

  /**
   * Update a dynamic template
   * Update an existing Handlebars template
   * @param id Template ID to update (required)
   * @param dataName Updated name for the template (optional)
   * @param dataBody Updated Handlebars template file (.hbs) (optional)
   * @return ApiResponse&lt;DynamicTemplateResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DynamicTemplateResponse> updateDynamicTemplateWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String dataName, @javax.annotation.Nullable File dataBody) throws ApiException {
    return updateDynamicTemplateWithHttpInfo(id, dataName, dataBody, null);
  }

  /**
   * Update a dynamic template
   * Update an existing Handlebars template
   * @param id Template ID to update (required)
   * @param dataName Updated name for the template (optional)
   * @param dataBody Updated Handlebars template file (.hbs) (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;DynamicTemplateResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DynamicTemplateResponse> updateDynamicTemplateWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String dataName, @javax.annotation.Nullable File dataBody, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = updateDynamicTemplateRequestBuilder(id, dataName, dataBody, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("updateDynamicTemplate", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<DynamicTemplateResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        DynamicTemplateResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<DynamicTemplateResponse>() {});
        

        return new ApiResponse<DynamicTemplateResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder updateDynamicTemplateRequestBuilder(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String dataName, @javax.annotation.Nullable File dataBody, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling updateDynamicTemplate");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/dynamic_templates/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    MultipartEntityBuilder multiPartBuilder = MultipartEntityBuilder.create();
    boolean hasFiles = false;
    if (dataName != null) {
        multiPartBuilder.addTextBody("data[name]", dataName.toString());
    }
    multiPartBuilder.addBinaryBody("data[body]", dataBody);
    hasFiles = true;
    HttpEntity entity = multiPartBuilder.build();
    HttpRequest.BodyPublisher formDataPublisher;
    if (hasFiles) {
        Pipe pipe;
        try {
            pipe = Pipe.open();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        new Thread(() -> {
            try (OutputStream outputStream = Channels.newOutputStream(pipe.sink())) {
                entity.writeTo(outputStream);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }).start();
        formDataPublisher = HttpRequest.BodyPublishers.ofInputStream(() -> Channels.newInputStream(pipe.source()));
    } else {
        ByteArrayOutputStream formOutputStream = new ByteArrayOutputStream();
        try {
            entity.writeTo(formOutputStream);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        byte[] formBytes = formOutputStream.toByteArray();
        formDataPublisher = HttpRequest.BodyPublishers
            .ofInputStream(() -> new ByteArrayInputStream(formBytes));
    }
    localVarRequestBuilder
        .header("Content-Type", entity.getContentType().getValue())
        .method("PATCH", formDataPublisher);
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
