/*
 * Paubox Email API
 * Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.paubox.api;

import com.paubox.ApiClient;
import com.paubox.ApiException;
import com.paubox.ApiResponse;
import com.paubox.Configuration;
import com.paubox.Pair;

import com.paubox.model.BulkSendRequest;
import com.paubox.model.BulkSendResponse;
import com.paubox.model.ErrorResponse;
import com.paubox.model.MessageReceiptErrorResponse;
import com.paubox.model.MessageReceiptResponse;
import com.paubox.model.SingleSendRequest;
import com.paubox.model.SingleSendResponse;
import java.util.UUID;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import org.apache.http.HttpEntity;
import org.apache.http.NameValuePair;
import org.apache.http.entity.mime.MultipartEntityBuilder;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.client.entity.UrlEncodedFormEntity;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-09T17:40:55.003620791Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class MessagesApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public MessagesApi() {
    this(Configuration.getDefaultApiClient());
  }

  public MessagesApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Get email disposition
   * Retrieve delivery status, open tracking, and click tracking information for a sent message
   * @param sourceTrackingId The tracking ID returned when the message was sent (required)
   * @return MessageReceiptResponse
   * @throws ApiException if fails to make API call
   */
  public MessageReceiptResponse getMessageReceipt(@javax.annotation.Nonnull UUID sourceTrackingId) throws ApiException {
    return getMessageReceipt(sourceTrackingId, null);
  }

  /**
   * Get email disposition
   * Retrieve delivery status, open tracking, and click tracking information for a sent message
   * @param sourceTrackingId The tracking ID returned when the message was sent (required)
   * @param headers Optional headers to include in the request
   * @return MessageReceiptResponse
   * @throws ApiException if fails to make API call
   */
  public MessageReceiptResponse getMessageReceipt(@javax.annotation.Nonnull UUID sourceTrackingId, Map<String, String> headers) throws ApiException {
    ApiResponse<MessageReceiptResponse> localVarResponse = getMessageReceiptWithHttpInfo(sourceTrackingId, headers);
    return localVarResponse.getData();
  }

  /**
   * Get email disposition
   * Retrieve delivery status, open tracking, and click tracking information for a sent message
   * @param sourceTrackingId The tracking ID returned when the message was sent (required)
   * @return ApiResponse&lt;MessageReceiptResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MessageReceiptResponse> getMessageReceiptWithHttpInfo(@javax.annotation.Nonnull UUID sourceTrackingId) throws ApiException {
    return getMessageReceiptWithHttpInfo(sourceTrackingId, null);
  }

  /**
   * Get email disposition
   * Retrieve delivery status, open tracking, and click tracking information for a sent message
   * @param sourceTrackingId The tracking ID returned when the message was sent (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;MessageReceiptResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MessageReceiptResponse> getMessageReceiptWithHttpInfo(@javax.annotation.Nonnull UUID sourceTrackingId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getMessageReceiptRequestBuilder(sourceTrackingId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getMessageReceipt", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<MessageReceiptResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        MessageReceiptResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<MessageReceiptResponse>() {});
        

        return new ApiResponse<MessageReceiptResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getMessageReceiptRequestBuilder(@javax.annotation.Nonnull UUID sourceTrackingId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'sourceTrackingId' is set
    if (sourceTrackingId == null) {
      throw new ApiException(400, "Missing the required parameter 'sourceTrackingId' when calling getMessageReceipt");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/message_receipt";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "sourceTrackingId";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("sourceTrackingId", sourceTrackingId));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Send multiple email messages (batch)
   * Sends multiple messages in one request. Paubox recommends batches of 50 or fewer. Source tracking IDs are returned in the same order as the messages array. 
   * @param bulkSendRequest  (required)
   * @return BulkSendResponse
   * @throws ApiException if fails to make API call
   */
  public BulkSendResponse sendBulkMessages(@javax.annotation.Nonnull BulkSendRequest bulkSendRequest) throws ApiException {
    return sendBulkMessages(bulkSendRequest, null);
  }

  /**
   * Send multiple email messages (batch)
   * Sends multiple messages in one request. Paubox recommends batches of 50 or fewer. Source tracking IDs are returned in the same order as the messages array. 
   * @param bulkSendRequest  (required)
   * @param headers Optional headers to include in the request
   * @return BulkSendResponse
   * @throws ApiException if fails to make API call
   */
  public BulkSendResponse sendBulkMessages(@javax.annotation.Nonnull BulkSendRequest bulkSendRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<BulkSendResponse> localVarResponse = sendBulkMessagesWithHttpInfo(bulkSendRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Send multiple email messages (batch)
   * Sends multiple messages in one request. Paubox recommends batches of 50 or fewer. Source tracking IDs are returned in the same order as the messages array. 
   * @param bulkSendRequest  (required)
   * @return ApiResponse&lt;BulkSendResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<BulkSendResponse> sendBulkMessagesWithHttpInfo(@javax.annotation.Nonnull BulkSendRequest bulkSendRequest) throws ApiException {
    return sendBulkMessagesWithHttpInfo(bulkSendRequest, null);
  }

  /**
   * Send multiple email messages (batch)
   * Sends multiple messages in one request. Paubox recommends batches of 50 or fewer. Source tracking IDs are returned in the same order as the messages array. 
   * @param bulkSendRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;BulkSendResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<BulkSendResponse> sendBulkMessagesWithHttpInfo(@javax.annotation.Nonnull BulkSendRequest bulkSendRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = sendBulkMessagesRequestBuilder(bulkSendRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("sendBulkMessages", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<BulkSendResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        BulkSendResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<BulkSendResponse>() {});
        

        return new ApiResponse<BulkSendResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder sendBulkMessagesRequestBuilder(@javax.annotation.Nonnull BulkSendRequest bulkSendRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'bulkSendRequest' is set
    if (bulkSendRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'bulkSendRequest' when calling sendBulkMessages");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/bulk_messages";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(bulkSendRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Send a single email message
   * 
   * @param singleSendRequest  (required)
   * @return SingleSendResponse
   * @throws ApiException if fails to make API call
   */
  public SingleSendResponse sendMessage(@javax.annotation.Nonnull SingleSendRequest singleSendRequest) throws ApiException {
    return sendMessage(singleSendRequest, null);
  }

  /**
   * Send a single email message
   * 
   * @param singleSendRequest  (required)
   * @param headers Optional headers to include in the request
   * @return SingleSendResponse
   * @throws ApiException if fails to make API call
   */
  public SingleSendResponse sendMessage(@javax.annotation.Nonnull SingleSendRequest singleSendRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<SingleSendResponse> localVarResponse = sendMessageWithHttpInfo(singleSendRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Send a single email message
   * 
   * @param singleSendRequest  (required)
   * @return ApiResponse&lt;SingleSendResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<SingleSendResponse> sendMessageWithHttpInfo(@javax.annotation.Nonnull SingleSendRequest singleSendRequest) throws ApiException {
    return sendMessageWithHttpInfo(singleSendRequest, null);
  }

  /**
   * Send a single email message
   * 
   * @param singleSendRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;SingleSendResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<SingleSendResponse> sendMessageWithHttpInfo(@javax.annotation.Nonnull SingleSendRequest singleSendRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = sendMessageRequestBuilder(singleSendRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("sendMessage", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<SingleSendResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        SingleSendResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<SingleSendResponse>() {});
        

        return new ApiResponse<SingleSendResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder sendMessageRequestBuilder(@javax.annotation.Nonnull SingleSendRequest singleSendRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'singleSendRequest' is set
    if (singleSendRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'singleSendRequest' when calling sendMessage");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/messages";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(singleSendRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
