/*
 * Paubox Email API
 * Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.paubox.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.paubox.ApiClient;
/**
 * BulkSendResponseMessagesInner
 */
@JsonPropertyOrder({
  BulkSendResponseMessagesInner.JSON_PROPERTY_SOURCE_TRACKING_ID,
  BulkSendResponseMessagesInner.JSON_PROPERTY_CUSTOM_HEADERS,
  BulkSendResponseMessagesInner.JSON_PROPERTY_DATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-09T17:40:55.003620791Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class BulkSendResponseMessagesInner {
  public static final String JSON_PROPERTY_SOURCE_TRACKING_ID = "sourceTrackingId";
  @javax.annotation.Nullable
  private String sourceTrackingId;

  public static final String JSON_PROPERTY_CUSTOM_HEADERS = "customHeaders";
  @javax.annotation.Nullable
  private Map<String, String> customHeaders = new HashMap<>();

  public static final String JSON_PROPERTY_DATA = "data";
  @javax.annotation.Nullable
  private String data;

  public BulkSendResponseMessagesInner() { 
  }

  public BulkSendResponseMessagesInner sourceTrackingId(@javax.annotation.Nullable String sourceTrackingId) {
    this.sourceTrackingId = sourceTrackingId;
    return this;
  }

  /**
   * Get sourceTrackingId
   * @return sourceTrackingId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SOURCE_TRACKING_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSourceTrackingId() {
    return sourceTrackingId;
  }


  @JsonProperty(value = JSON_PROPERTY_SOURCE_TRACKING_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourceTrackingId(@javax.annotation.Nullable String sourceTrackingId) {
    this.sourceTrackingId = sourceTrackingId;
  }


  public BulkSendResponseMessagesInner customHeaders(@javax.annotation.Nullable Map<String, String> customHeaders) {
    this.customHeaders = customHeaders;
    return this;
  }

  public BulkSendResponseMessagesInner putCustomHeadersItem(String key, String customHeadersItem) {
    if (this.customHeaders == null) {
      this.customHeaders = new HashMap<>();
    }
    this.customHeaders.put(key, customHeadersItem);
    return this;
  }

  /**
   * Get customHeaders
   * @return customHeaders
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOM_HEADERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, String> getCustomHeaders() {
    return customHeaders;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOM_HEADERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomHeaders(@javax.annotation.Nullable Map<String, String> customHeaders) {
    this.customHeaders = customHeaders;
  }


  public BulkSendResponseMessagesInner data(@javax.annotation.Nullable String data) {
    this.data = data;
    return this;
  }

  /**
   * Get data
   * @return data
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getData() {
    return data;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(@javax.annotation.Nullable String data) {
    this.data = data;
  }


  /**
   * Return true if this BulkSendResponse_messages_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkSendResponseMessagesInner bulkSendResponseMessagesInner = (BulkSendResponseMessagesInner) o;
    return Objects.equals(this.sourceTrackingId, bulkSendResponseMessagesInner.sourceTrackingId) &&
        Objects.equals(this.customHeaders, bulkSendResponseMessagesInner.customHeaders) &&
        Objects.equals(this.data, bulkSendResponseMessagesInner.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceTrackingId, customHeaders, data);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkSendResponseMessagesInner {\n");
    sb.append("    sourceTrackingId: ").append(toIndentedString(sourceTrackingId)).append("\n");
    sb.append("    customHeaders: ").append(toIndentedString(customHeaders)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `sourceTrackingId` to the URL query string
    if (getSourceTrackingId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssourceTrackingId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSourceTrackingId()))));
    }

    // add `customHeaders` to the URL query string
    if (getCustomHeaders() != null) {
      for (String _key : getCustomHeaders().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%scustomHeaders%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getCustomHeaders().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getCustomHeaders().get(_key)))));
      }
    }

    // add `data` to the URL query string
    if (getData() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdata%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getData()))));
    }

    return joiner.toString();
  }
}

