/*
 * Paubox Email API
 * Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.paubox.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.paubox.ApiClient;
/**
 * DeliveryStatus
 */
@JsonPropertyOrder({
  DeliveryStatus.JSON_PROPERTY_DELIVERY_STATUS,
  DeliveryStatus.JSON_PROPERTY_DELIVERY_TIME,
  DeliveryStatus.JSON_PROPERTY_OPENED_STATUS,
  DeliveryStatus.JSON_PROPERTY_OPENED_TIME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-09T17:40:55.003620791Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class DeliveryStatus {
  /**
   * The delivery status of the message
   */
  public enum DeliveryStatusEnum {
    PROCESSING(String.valueOf("processing")),
    
    TLS_NOT_OFFERED_SENDING_VIA_SECURE_PORTAL(String.valueOf("TLS not offered, sending via Secure Portal")),
    
    SOFT_BOUNCED(String.valueOf("soft bounced")),
    
    SOFT_BOUNCED_MAILBOX_FULL(String.valueOf("soft bounced - mailbox full")),
    
    HARD_BOUNCED(String.valueOf("hard bounced")),
    
    INTERNAL_ERROR_PLEASE_CHECK_BACK_LATER_(String.valueOf("Internal error. Please check back later.")),
    
    DELIVERED(String.valueOf("delivered")),
    
    DELIVERED_VIA_SECURE_PORTAL(String.valueOf("delivered via secure portal"));

    private String value;

    DeliveryStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DeliveryStatusEnum fromValue(String value) {
      for (DeliveryStatusEnum b : DeliveryStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_DELIVERY_STATUS = "deliveryStatus";
  @javax.annotation.Nonnull
  private DeliveryStatusEnum deliveryStatus;

  public static final String JSON_PROPERTY_DELIVERY_TIME = "deliveryTime";
  @javax.annotation.Nullable
  private String deliveryTime;

  /**
   * Whether the message was opened (single recipient only)
   */
  public enum OpenedStatusEnum {
    OPENED(String.valueOf("opened")),
    
    NOT_OPENED(String.valueOf("not opened"));

    private String value;

    OpenedStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OpenedStatusEnum fromValue(String value) {
      for (OpenedStatusEnum b : OpenedStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OPENED_STATUS = "openedStatus";
  @javax.annotation.Nullable
  private OpenedStatusEnum openedStatus;

  public static final String JSON_PROPERTY_OPENED_TIME = "openedTime";
  @javax.annotation.Nullable
  private String openedTime;

  public DeliveryStatus() { 
  }

  public DeliveryStatus deliveryStatus(@javax.annotation.Nonnull DeliveryStatusEnum deliveryStatus) {
    this.deliveryStatus = deliveryStatus;
    return this;
  }

  /**
   * The delivery status of the message
   * @return deliveryStatus
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DELIVERY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public DeliveryStatusEnum getDeliveryStatus() {
    return deliveryStatus;
  }


  @JsonProperty(value = JSON_PROPERTY_DELIVERY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDeliveryStatus(@javax.annotation.Nonnull DeliveryStatusEnum deliveryStatus) {
    this.deliveryStatus = deliveryStatus;
  }


  public DeliveryStatus deliveryTime(@javax.annotation.Nullable String deliveryTime) {
    this.deliveryTime = deliveryTime;
    return this;
  }

  /**
   * The time when the message was delivered (if applicable)
   * @return deliveryTime
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DELIVERY_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDeliveryTime() {
    return deliveryTime;
  }


  @JsonProperty(value = JSON_PROPERTY_DELIVERY_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeliveryTime(@javax.annotation.Nullable String deliveryTime) {
    this.deliveryTime = deliveryTime;
  }


  public DeliveryStatus openedStatus(@javax.annotation.Nullable OpenedStatusEnum openedStatus) {
    this.openedStatus = openedStatus;
    return this;
  }

  /**
   * Whether the message was opened (single recipient only)
   * @return openedStatus
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OPENED_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OpenedStatusEnum getOpenedStatus() {
    return openedStatus;
  }


  @JsonProperty(value = JSON_PROPERTY_OPENED_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOpenedStatus(@javax.annotation.Nullable OpenedStatusEnum openedStatus) {
    this.openedStatus = openedStatus;
  }


  public DeliveryStatus openedTime(@javax.annotation.Nullable String openedTime) {
    this.openedTime = openedTime;
    return this;
  }

  /**
   * The time when the message was first opened (single recipient only)
   * @return openedTime
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OPENED_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getOpenedTime() {
    return openedTime;
  }


  @JsonProperty(value = JSON_PROPERTY_OPENED_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOpenedTime(@javax.annotation.Nullable String openedTime) {
    this.openedTime = openedTime;
  }


  /**
   * Return true if this DeliveryStatus object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeliveryStatus deliveryStatus = (DeliveryStatus) o;
    return Objects.equals(this.deliveryStatus, deliveryStatus.deliveryStatus) &&
        Objects.equals(this.deliveryTime, deliveryStatus.deliveryTime) &&
        Objects.equals(this.openedStatus, deliveryStatus.openedStatus) &&
        Objects.equals(this.openedTime, deliveryStatus.openedTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deliveryStatus, deliveryTime, openedStatus, openedTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeliveryStatus {\n");
    sb.append("    deliveryStatus: ").append(toIndentedString(deliveryStatus)).append("\n");
    sb.append("    deliveryTime: ").append(toIndentedString(deliveryTime)).append("\n");
    sb.append("    openedStatus: ").append(toIndentedString(openedStatus)).append("\n");
    sb.append("    openedTime: ").append(toIndentedString(openedTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `deliveryStatus` to the URL query string
    if (getDeliveryStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdeliveryStatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeliveryStatus()))));
    }

    // add `deliveryTime` to the URL query string
    if (getDeliveryTime() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdeliveryTime%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeliveryTime()))));
    }

    // add `openedStatus` to the URL query string
    if (getOpenedStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sopenedStatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOpenedStatus()))));
    }

    // add `openedTime` to the URL query string
    if (getOpenedTime() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sopenedTime%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOpenedTime()))));
    }

    return joiner.toString();
  }
}

