/*
 * Paubox Email API
 * Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.paubox.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.paubox.model.DynamicTemplateResponse;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.paubox.ApiClient;
/**
 * DynamicTemplateListResponse
 */
@JsonPropertyOrder({
  DynamicTemplateListResponse.JSON_PROPERTY_TEMPLATES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-09T17:40:55.003620791Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class DynamicTemplateListResponse {
  public static final String JSON_PROPERTY_TEMPLATES = "templates";
  @javax.annotation.Nullable
  private List<DynamicTemplateResponse> templates = new ArrayList<>();

  public DynamicTemplateListResponse() { 
  }

  public DynamicTemplateListResponse templates(@javax.annotation.Nullable List<DynamicTemplateResponse> templates) {
    this.templates = templates;
    return this;
  }

  public DynamicTemplateListResponse addTemplatesItem(DynamicTemplateResponse templatesItem) {
    if (this.templates == null) {
      this.templates = new ArrayList<>();
    }
    this.templates.add(templatesItem);
    return this;
  }

  /**
   * Get templates
   * @return templates
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TEMPLATES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<DynamicTemplateResponse> getTemplates() {
    return templates;
  }


  @JsonProperty(value = JSON_PROPERTY_TEMPLATES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTemplates(@javax.annotation.Nullable List<DynamicTemplateResponse> templates) {
    this.templates = templates;
  }


  /**
   * Return true if this DynamicTemplateListResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DynamicTemplateListResponse dynamicTemplateListResponse = (DynamicTemplateListResponse) o;
    return Objects.equals(this.templates, dynamicTemplateListResponse.templates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(templates);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DynamicTemplateListResponse {\n");
    sb.append("    templates: ").append(toIndentedString(templates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `templates` to the URL query string
    if (getTemplates() != null) {
      for (int i = 0; i < getTemplates().size(); i++) {
        if (getTemplates().get(i) != null) {
          joiner.add(getTemplates().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%stemplates%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

