/*
 * Paubox Email API
 * Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.paubox.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.paubox.ApiClient;
/**
 * MessageHeaders
 */
@JsonPropertyOrder({
  MessageHeaders.JSON_PROPERTY_SUBJECT,
  MessageHeaders.JSON_PROPERTY_FROM,
  MessageHeaders.JSON_PROPERTY_REPLY_TO,
  MessageHeaders.JSON_PROPERTY_LIST_UNSUBSCRIBE,
  MessageHeaders.JSON_PROPERTY_LIST_UNSUBSCRIBE_POST,
  MessageHeaders.JSON_PROPERTY_X_CUSTOM_HEADER,
  MessageHeaders.JSON_PROPERTY_ADDITIONAL_PROPERTIES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-09T17:40:55.003620791Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class MessageHeaders {
  public static final String JSON_PROPERTY_SUBJECT = "subject";
  @javax.annotation.Nonnull
  private String subject;

  public static final String JSON_PROPERTY_FROM = "from";
  @javax.annotation.Nonnull
  private String from;

  public static final String JSON_PROPERTY_REPLY_TO = "reply-to";
  @javax.annotation.Nullable
  private String replyTo;

  public static final String JSON_PROPERTY_LIST_UNSUBSCRIBE = "List-Unsubscribe";
  @javax.annotation.Nullable
  private String listUnsubscribe;

  public static final String JSON_PROPERTY_LIST_UNSUBSCRIBE_POST = "List-Unsubscribe-Post";
  @javax.annotation.Nullable
  private String listUnsubscribePost;

  public static final String JSON_PROPERTY_X_CUSTOM_HEADER = "x-custom-header";
  @javax.annotation.Nullable
  private String xCustomHeader;

  public static final String JSON_PROPERTY_ADDITIONAL_PROPERTIES = "additionalProperties";
  @javax.annotation.Nullable
  private String additionalProperties;

  public MessageHeaders() { 
  }

  public MessageHeaders subject(@javax.annotation.Nonnull String subject) {
    this.subject = subject;
    return this;
  }

  /**
   * Get subject
   * @return subject
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SUBJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSubject() {
    return subject;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubject(@javax.annotation.Nonnull String subject) {
    this.subject = subject;
  }


  public MessageHeaders from(@javax.annotation.Nonnull String from) {
    this.from = from;
    return this;
  }

  /**
   * Must match the verified domain of your API key.
   * @return from
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FROM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getFrom() {
    return from;
  }


  @JsonProperty(value = JSON_PROPERTY_FROM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFrom(@javax.annotation.Nonnull String from) {
    this.from = from;
  }


  public MessageHeaders replyTo(@javax.annotation.Nullable String replyTo) {
    this.replyTo = replyTo;
    return this;
  }

  /**
   * Reply-to address; must match a verified domain if different from from.
   * @return replyTo
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REPLY_TO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getReplyTo() {
    return replyTo;
  }


  @JsonProperty(value = JSON_PROPERTY_REPLY_TO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReplyTo(@javax.annotation.Nullable String replyTo) {
    this.replyTo = replyTo;
  }


  public MessageHeaders listUnsubscribe(@javax.annotation.Nullable String listUnsubscribe) {
    this.listUnsubscribe = listUnsubscribe;
    return this;
  }

  /**
   * Insert a List-Unsubscribe header (mailto and/or http). See RFC guidance for syntax. 
   * @return listUnsubscribe
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LIST_UNSUBSCRIBE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getListUnsubscribe() {
    return listUnsubscribe;
  }


  @JsonProperty(value = JSON_PROPERTY_LIST_UNSUBSCRIBE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setListUnsubscribe(@javax.annotation.Nullable String listUnsubscribe) {
    this.listUnsubscribe = listUnsubscribe;
  }


  public MessageHeaders listUnsubscribePost(@javax.annotation.Nullable String listUnsubscribePost) {
    this.listUnsubscribePost = listUnsubscribePost;
    return this;
  }

  /**
   * Used in conjunction with List-Unsubscribe header.
   * @return listUnsubscribePost
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LIST_UNSUBSCRIBE_POST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getListUnsubscribePost() {
    return listUnsubscribePost;
  }


  @JsonProperty(value = JSON_PROPERTY_LIST_UNSUBSCRIBE_POST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setListUnsubscribePost(@javax.annotation.Nullable String listUnsubscribePost) {
    this.listUnsubscribePost = listUnsubscribePost;
  }


  public MessageHeaders xCustomHeader(@javax.annotation.Nullable String xCustomHeader) {
    this.xCustomHeader = xCustomHeader;
    return this;
  }

  /**
   * Example custom header; any custom header may be added with an X- prefix.
   * @return xCustomHeader
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_X_CUSTOM_HEADER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getxCustomHeader() {
    return xCustomHeader;
  }


  @JsonProperty(value = JSON_PROPERTY_X_CUSTOM_HEADER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setxCustomHeader(@javax.annotation.Nullable String xCustomHeader) {
    this.xCustomHeader = xCustomHeader;
  }


  public MessageHeaders additionalProperties(@javax.annotation.Nullable String additionalProperties) {
    this.additionalProperties = additionalProperties;
    return this;
  }

  /**
   * Any additional X- prefixed custom header values.
   * @return additionalProperties
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ADDITIONAL_PROPERTIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAdditionalProperties() {
    return additionalProperties;
  }


  @JsonProperty(value = JSON_PROPERTY_ADDITIONAL_PROPERTIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdditionalProperties(@javax.annotation.Nullable String additionalProperties) {
    this.additionalProperties = additionalProperties;
  }


  /**
   * Return true if this MessageHeaders object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessageHeaders messageHeaders = (MessageHeaders) o;
    return Objects.equals(this.subject, messageHeaders.subject) &&
        Objects.equals(this.from, messageHeaders.from) &&
        Objects.equals(this.replyTo, messageHeaders.replyTo) &&
        Objects.equals(this.listUnsubscribe, messageHeaders.listUnsubscribe) &&
        Objects.equals(this.listUnsubscribePost, messageHeaders.listUnsubscribePost) &&
        Objects.equals(this.xCustomHeader, messageHeaders.xCustomHeader) &&
        Objects.equals(this.additionalProperties, messageHeaders.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subject, from, replyTo, listUnsubscribe, listUnsubscribePost, xCustomHeader, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessageHeaders {\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    replyTo: ").append(toIndentedString(replyTo)).append("\n");
    sb.append("    listUnsubscribe: ").append(toIndentedString(listUnsubscribe)).append("\n");
    sb.append("    listUnsubscribePost: ").append(toIndentedString(listUnsubscribePost)).append("\n");
    sb.append("    xCustomHeader: ").append(toIndentedString(xCustomHeader)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `subject` to the URL query string
    if (getSubject() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssubject%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSubject()))));
    }

    // add `from` to the URL query string
    if (getFrom() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfrom%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFrom()))));
    }

    // add `reply-to` to the URL query string
    if (getReplyTo() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sreply-to%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReplyTo()))));
    }

    // add `List-Unsubscribe` to the URL query string
    if (getListUnsubscribe() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sList-Unsubscribe%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getListUnsubscribe()))));
    }

    // add `List-Unsubscribe-Post` to the URL query string
    if (getListUnsubscribePost() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sList-Unsubscribe-Post%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getListUnsubscribePost()))));
    }

    // add `x-custom-header` to the URL query string
    if (getxCustomHeader() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sx-custom-header%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getxCustomHeader()))));
    }

    // add `additionalProperties` to the URL query string
    if (getAdditionalProperties() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sadditionalProperties%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAdditionalProperties()))));
    }

    return joiner.toString();
  }
}

