/*
 * Paubox Email API
 * Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.paubox.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.paubox.ApiClient;
/**
 * MessageContent
 */
@JsonPropertyOrder({
  MessageContent.JSON_PROPERTY_TEXT_PLAIN,
  MessageContent.JSON_PROPERTY_TEXT_HTML
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-09T17:40:55.003620791Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class MessageContent {
  public static final String JSON_PROPERTY_TEXT_PLAIN = "text/plain";
  @javax.annotation.Nullable
  private String textPlain;

  public static final String JSON_PROPERTY_TEXT_HTML = "text/html";
  @javax.annotation.Nullable
  private String textHtml;

  public MessageContent() { 
  }

  public MessageContent textPlain(@javax.annotation.Nullable String textPlain) {
    this.textPlain = textPlain;
    return this;
  }

  /**
   * Plain text message body. Required if text/html is not provided.
   * @return textPlain
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TEXT_PLAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTextPlain() {
    return textPlain;
  }


  @JsonProperty(value = JSON_PROPERTY_TEXT_PLAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTextPlain(@javax.annotation.Nullable String textPlain) {
    this.textPlain = textPlain;
  }


  public MessageContent textHtml(@javax.annotation.Nullable String textHtml) {
    this.textHtml = textHtml;
    return this;
  }

  /**
   * HTML message body. May be HTML-escaped, base64-encoded, or a valid unescaped string. CSS in &lt;style&gt; tags will be rendered inline. 
   * @return textHtml
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TEXT_HTML, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTextHtml() {
    return textHtml;
  }


  @JsonProperty(value = JSON_PROPERTY_TEXT_HTML, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTextHtml(@javax.annotation.Nullable String textHtml) {
    this.textHtml = textHtml;
  }


  /**
   * Return true if this MessageContent object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessageContent messageContent = (MessageContent) o;
    return Objects.equals(this.textPlain, messageContent.textPlain) &&
        Objects.equals(this.textHtml, messageContent.textHtml);
  }

  @Override
  public int hashCode() {
    return Objects.hash(textPlain, textHtml);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessageContent {\n");
    sb.append("    textPlain: ").append(toIndentedString(textPlain)).append("\n");
    sb.append("    textHtml: ").append(toIndentedString(textHtml)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    return joiner.toString();
  }
}

