/*
 * Paubox Email API
 * Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.paubox.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.paubox.model.Attachment;
import com.paubox.model.MessageContent;
import com.paubox.model.MessageHeaders;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.paubox.ApiClient;
/**
 * Message
 */
@JsonPropertyOrder({
  Message.JSON_PROPERTY_RECIPIENTS,
  Message.JSON_PROPERTY_BCC,
  Message.JSON_PROPERTY_CC,
  Message.JSON_PROPERTY_HEADERS,
  Message.JSON_PROPERTY_ALLOW_NON_T_L_S,
  Message.JSON_PROPERTY_FORCE_SECURE_NOTIFICATION,
  Message.JSON_PROPERTY_CONTENT,
  Message.JSON_PROPERTY_ATTACHMENTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-09T17:40:55.003620791Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class Message {
  public static final String JSON_PROPERTY_RECIPIENTS = "recipients";
  @javax.annotation.Nonnull
  private List<String> recipients = new ArrayList<>();

  public static final String JSON_PROPERTY_BCC = "bcc";
  @javax.annotation.Nullable
  private List<String> bcc = new ArrayList<>();

  public static final String JSON_PROPERTY_CC = "cc";
  @javax.annotation.Nullable
  private List<String> cc = new ArrayList<>();

  public static final String JSON_PROPERTY_HEADERS = "headers";
  @javax.annotation.Nonnull
  private MessageHeaders headers;

  public static final String JSON_PROPERTY_ALLOW_NON_T_L_S = "allowNonTLS";
  @javax.annotation.Nullable
  private Boolean allowNonTLS = false;

  public static final String JSON_PROPERTY_FORCE_SECURE_NOTIFICATION = "forceSecureNotification";
  @javax.annotation.Nullable
  private Boolean forceSecureNotification = false;

  public static final String JSON_PROPERTY_CONTENT = "content";
  @javax.annotation.Nullable
  private MessageContent content;

  public static final String JSON_PROPERTY_ATTACHMENTS = "attachments";
  @javax.annotation.Nullable
  private List<Attachment> attachments = new ArrayList<>();

  public Message() { 
  }

  public Message recipients(@javax.annotation.Nonnull List<String> recipients) {
    this.recipients = recipients;
    return this;
  }

  public Message addRecipientsItem(String recipientsItem) {
    if (this.recipients == null) {
      this.recipients = new ArrayList<>();
    }
    this.recipients.add(recipientsItem);
    return this;
  }

  /**
   * Get recipients
   * @return recipients
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RECIPIENTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getRecipients() {
    return recipients;
  }


  @JsonProperty(value = JSON_PROPERTY_RECIPIENTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRecipients(@javax.annotation.Nonnull List<String> recipients) {
    this.recipients = recipients;
  }


  public Message bcc(@javax.annotation.Nullable List<String> bcc) {
    this.bcc = bcc;
    return this;
  }

  public Message addBccItem(String bccItem) {
    if (this.bcc == null) {
      this.bcc = new ArrayList<>();
    }
    this.bcc.add(bccItem);
    return this;
  }

  /**
   * Get bcc
   * @return bcc
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BCC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getBcc() {
    return bcc;
  }


  @JsonProperty(value = JSON_PROPERTY_BCC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBcc(@javax.annotation.Nullable List<String> bcc) {
    this.bcc = bcc;
  }


  public Message cc(@javax.annotation.Nullable List<String> cc) {
    this.cc = cc;
    return this;
  }

  public Message addCcItem(String ccItem) {
    if (this.cc == null) {
      this.cc = new ArrayList<>();
    }
    this.cc.add(ccItem);
    return this;
  }

  /**
   * Get cc
   * @return cc
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getCc() {
    return cc;
  }


  @JsonProperty(value = JSON_PROPERTY_CC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCc(@javax.annotation.Nullable List<String> cc) {
    this.cc = cc;
  }


  public Message headers(@javax.annotation.Nonnull MessageHeaders headers) {
    this.headers = headers;
    return this;
  }

  /**
   * Get headers
   * @return headers
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_HEADERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public MessageHeaders getHeaders() {
    return headers;
  }


  @JsonProperty(value = JSON_PROPERTY_HEADERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHeaders(@javax.annotation.Nonnull MessageHeaders headers) {
    this.headers = headers;
  }


  public Message allowNonTLS(@javax.annotation.Nullable Boolean allowNonTLS) {
    this.allowNonTLS = allowNonTLS;
    return this;
  }

  /**
   * Allow delivery over non-TLS rather than converting to a Secure Portal message. Not HIPAA-compliant if the message contains PHI. 
   * @return allowNonTLS
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ALLOW_NON_T_L_S, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getAllowNonTLS() {
    return allowNonTLS;
  }


  @JsonProperty(value = JSON_PROPERTY_ALLOW_NON_T_L_S, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllowNonTLS(@javax.annotation.Nullable Boolean allowNonTLS) {
    this.allowNonTLS = allowNonTLS;
  }


  public Message forceSecureNotification(@javax.annotation.Nullable Boolean forceSecureNotification) {
    this.forceSecureNotification = forceSecureNotification;
    return this;
  }

  /**
   * Force delivery as a Paubox Secure Message; recipient gets a pickup notification with a link. 
   * @return forceSecureNotification
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FORCE_SECURE_NOTIFICATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getForceSecureNotification() {
    return forceSecureNotification;
  }


  @JsonProperty(value = JSON_PROPERTY_FORCE_SECURE_NOTIFICATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setForceSecureNotification(@javax.annotation.Nullable Boolean forceSecureNotification) {
    this.forceSecureNotification = forceSecureNotification;
  }


  public Message content(@javax.annotation.Nullable MessageContent content) {
    this.content = content;
    return this;
  }

  /**
   * Get content
   * @return content
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public MessageContent getContent() {
    return content;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContent(@javax.annotation.Nullable MessageContent content) {
    this.content = content;
  }


  public Message attachments(@javax.annotation.Nullable List<Attachment> attachments) {
    this.attachments = attachments;
    return this;
  }

  public Message addAttachmentsItem(Attachment attachmentsItem) {
    if (this.attachments == null) {
      this.attachments = new ArrayList<>();
    }
    this.attachments.add(attachmentsItem);
    return this;
  }

  /**
   * Get attachments
   * @return attachments
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ATTACHMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<Attachment> getAttachments() {
    return attachments;
  }


  @JsonProperty(value = JSON_PROPERTY_ATTACHMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAttachments(@javax.annotation.Nullable List<Attachment> attachments) {
    this.attachments = attachments;
  }


  /**
   * Return true if this Message object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Message message = (Message) o;
    return Objects.equals(this.recipients, message.recipients) &&
        Objects.equals(this.bcc, message.bcc) &&
        Objects.equals(this.cc, message.cc) &&
        Objects.equals(this.headers, message.headers) &&
        Objects.equals(this.allowNonTLS, message.allowNonTLS) &&
        Objects.equals(this.forceSecureNotification, message.forceSecureNotification) &&
        Objects.equals(this.content, message.content) &&
        Objects.equals(this.attachments, message.attachments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(recipients, bcc, cc, headers, allowNonTLS, forceSecureNotification, content, attachments);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Message {\n");
    sb.append("    recipients: ").append(toIndentedString(recipients)).append("\n");
    sb.append("    bcc: ").append(toIndentedString(bcc)).append("\n");
    sb.append("    cc: ").append(toIndentedString(cc)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    allowNonTLS: ").append(toIndentedString(allowNonTLS)).append("\n");
    sb.append("    forceSecureNotification: ").append(toIndentedString(forceSecureNotification)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `recipients` to the URL query string
    if (getRecipients() != null) {
      for (int i = 0; i < getRecipients().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%srecipients%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getRecipients().get(i)))));
      }
    }

    // add `bcc` to the URL query string
    if (getBcc() != null) {
      for (int i = 0; i < getBcc().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sbcc%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getBcc().get(i)))));
      }
    }

    // add `cc` to the URL query string
    if (getCc() != null) {
      for (int i = 0; i < getCc().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%scc%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getCc().get(i)))));
      }
    }

    // add `headers` to the URL query string
    if (getHeaders() != null) {
      joiner.add(getHeaders().toUrlQueryString(prefix + "headers" + suffix));
    }

    // add `allowNonTLS` to the URL query string
    if (getAllowNonTLS() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sallowNonTLS%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAllowNonTLS()))));
    }

    // add `forceSecureNotification` to the URL query string
    if (getForceSecureNotification() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sforceSecureNotification%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getForceSecureNotification()))));
    }

    // add `content` to the URL query string
    if (getContent() != null) {
      joiner.add(getContent().toUrlQueryString(prefix + "content" + suffix));
    }

    // add `attachments` to the URL query string
    if (getAttachments() != null) {
      for (int i = 0; i < getAttachments().size(); i++) {
        if (getAttachments().get(i) != null) {
          joiner.add(getAttachments().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sattachments%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

