/*
 * Paubox Email API
 * Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.paubox.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.paubox.model.DeliveryStatus;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.paubox.ApiClient;
/**
 * MessageDelivery
 */
@JsonPropertyOrder({
  MessageDelivery.JSON_PROPERTY_RECIPIENT,
  MessageDelivery.JSON_PROPERTY_STATUS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-09T17:40:55.003620791Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class MessageDelivery {
  public static final String JSON_PROPERTY_RECIPIENT = "recipient";
  @javax.annotation.Nonnull
  private String recipient;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nonnull
  private DeliveryStatus status;

  public MessageDelivery() { 
  }

  public MessageDelivery recipient(@javax.annotation.Nonnull String recipient) {
    this.recipient = recipient;
    return this;
  }

  /**
   * The recipient email address
   * @return recipient
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RECIPIENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getRecipient() {
    return recipient;
  }


  @JsonProperty(value = JSON_PROPERTY_RECIPIENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRecipient(@javax.annotation.Nonnull String recipient) {
    this.recipient = recipient;
  }


  public MessageDelivery status(@javax.annotation.Nonnull DeliveryStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public DeliveryStatus getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@javax.annotation.Nonnull DeliveryStatus status) {
    this.status = status;
  }


  /**
   * Return true if this MessageDelivery object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessageDelivery messageDelivery = (MessageDelivery) o;
    return Objects.equals(this.recipient, messageDelivery.recipient) &&
        Objects.equals(this.status, messageDelivery.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(recipient, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessageDelivery {\n");
    sb.append("    recipient: ").append(toIndentedString(recipient)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `recipient` to the URL query string
    if (getRecipient() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srecipient%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRecipient()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(getStatus().toUrlQueryString(prefix + "status" + suffix));
    }

    return joiner.toString();
  }
}

