/*
 * Paubox Email API
 * Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.paubox.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.paubox.model.ClickData;
import com.paubox.model.MessageDelivery;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.paubox.ApiClient;
/**
 * MessageReceiptResponseDataMessage
 */
@JsonPropertyOrder({
  MessageReceiptResponseDataMessage.JSON_PROPERTY_ID,
  MessageReceiptResponseDataMessage.JSON_PROPERTY_MESSAGE_DELIVERIES,
  MessageReceiptResponseDataMessage.JSON_PROPERTY_TOTAL_OPENS,
  MessageReceiptResponseDataMessage.JSON_PROPERTY_DISTINCT_OPENS,
  MessageReceiptResponseDataMessage.JSON_PROPERTY_TOTAL_CLICK_COUNT,
  MessageReceiptResponseDataMessage.JSON_PROPERTY_CLICKS_PER_LINK,
  MessageReceiptResponseDataMessage.JSON_PROPERTY_UNSUBSCRIBED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-09T17:40:55.003620791Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class MessageReceiptResponseDataMessage {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_MESSAGE_DELIVERIES = "message_deliveries";
  @javax.annotation.Nonnull
  private List<MessageDelivery> messageDeliveries = new ArrayList<>();

  public static final String JSON_PROPERTY_TOTAL_OPENS = "total_opens";
  @javax.annotation.Nullable
  private Integer totalOpens;

  public static final String JSON_PROPERTY_DISTINCT_OPENS = "distinct_opens";
  @javax.annotation.Nullable
  private Integer distinctOpens;

  public static final String JSON_PROPERTY_TOTAL_CLICK_COUNT = "total_click_count";
  @javax.annotation.Nullable
  private Integer totalClickCount;

  public static final String JSON_PROPERTY_CLICKS_PER_LINK = "clicks_per_link";
  @javax.annotation.Nullable
  private List<ClickData> clicksPerLink = new ArrayList<>();

  public static final String JSON_PROPERTY_UNSUBSCRIBED = "unsubscribed";
  @javax.annotation.Nullable
  private Boolean unsubscribed;

  public MessageReceiptResponseDataMessage() { 
  }

  public MessageReceiptResponseDataMessage id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * The message ID
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public MessageReceiptResponseDataMessage messageDeliveries(@javax.annotation.Nonnull List<MessageDelivery> messageDeliveries) {
    this.messageDeliveries = messageDeliveries;
    return this;
  }

  public MessageReceiptResponseDataMessage addMessageDeliveriesItem(MessageDelivery messageDeliveriesItem) {
    if (this.messageDeliveries == null) {
      this.messageDeliveries = new ArrayList<>();
    }
    this.messageDeliveries.add(messageDeliveriesItem);
    return this;
  }

  /**
   * Get messageDeliveries
   * @return messageDeliveries
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGE_DELIVERIES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<MessageDelivery> getMessageDeliveries() {
    return messageDeliveries;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE_DELIVERIES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessageDeliveries(@javax.annotation.Nonnull List<MessageDelivery> messageDeliveries) {
    this.messageDeliveries = messageDeliveries;
  }


  public MessageReceiptResponseDataMessage totalOpens(@javax.annotation.Nullable Integer totalOpens) {
    this.totalOpens = totalOpens;
    return this;
  }

  /**
   * Total number of opens (single recipient only)
   * @return totalOpens
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_OPENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTotalOpens() {
    return totalOpens;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_OPENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalOpens(@javax.annotation.Nullable Integer totalOpens) {
    this.totalOpens = totalOpens;
  }


  public MessageReceiptResponseDataMessage distinctOpens(@javax.annotation.Nullable Integer distinctOpens) {
    this.distinctOpens = distinctOpens;
    return this;
  }

  /**
   * Number of distinct opens (single recipient only)
   * @return distinctOpens
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DISTINCT_OPENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getDistinctOpens() {
    return distinctOpens;
  }


  @JsonProperty(value = JSON_PROPERTY_DISTINCT_OPENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDistinctOpens(@javax.annotation.Nullable Integer distinctOpens) {
    this.distinctOpens = distinctOpens;
  }


  public MessageReceiptResponseDataMessage totalClickCount(@javax.annotation.Nullable Integer totalClickCount) {
    this.totalClickCount = totalClickCount;
    return this;
  }

  /**
   * Total number of clicks (single recipient only)
   * @return totalClickCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_CLICK_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTotalClickCount() {
    return totalClickCount;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_CLICK_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalClickCount(@javax.annotation.Nullable Integer totalClickCount) {
    this.totalClickCount = totalClickCount;
  }


  public MessageReceiptResponseDataMessage clicksPerLink(@javax.annotation.Nullable List<ClickData> clicksPerLink) {
    this.clicksPerLink = clicksPerLink;
    return this;
  }

  public MessageReceiptResponseDataMessage addClicksPerLinkItem(ClickData clicksPerLinkItem) {
    if (this.clicksPerLink == null) {
      this.clicksPerLink = new ArrayList<>();
    }
    this.clicksPerLink.add(clicksPerLinkItem);
    return this;
  }

  /**
   * Click tracking data per link (single recipient only)
   * @return clicksPerLink
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CLICKS_PER_LINK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<ClickData> getClicksPerLink() {
    return clicksPerLink;
  }


  @JsonProperty(value = JSON_PROPERTY_CLICKS_PER_LINK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClicksPerLink(@javax.annotation.Nullable List<ClickData> clicksPerLink) {
    this.clicksPerLink = clicksPerLink;
  }


  public MessageReceiptResponseDataMessage unsubscribed(@javax.annotation.Nullable Boolean unsubscribed) {
    this.unsubscribed = unsubscribed;
    return this;
  }

  /**
   * Whether the recipient has unsubscribed (single recipient only)
   * @return unsubscribed
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UNSUBSCRIBED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getUnsubscribed() {
    return unsubscribed;
  }


  @JsonProperty(value = JSON_PROPERTY_UNSUBSCRIBED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnsubscribed(@javax.annotation.Nullable Boolean unsubscribed) {
    this.unsubscribed = unsubscribed;
  }


  /**
   * Return true if this MessageReceiptResponse_data_message object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessageReceiptResponseDataMessage messageReceiptResponseDataMessage = (MessageReceiptResponseDataMessage) o;
    return Objects.equals(this.id, messageReceiptResponseDataMessage.id) &&
        Objects.equals(this.messageDeliveries, messageReceiptResponseDataMessage.messageDeliveries) &&
        Objects.equals(this.totalOpens, messageReceiptResponseDataMessage.totalOpens) &&
        Objects.equals(this.distinctOpens, messageReceiptResponseDataMessage.distinctOpens) &&
        Objects.equals(this.totalClickCount, messageReceiptResponseDataMessage.totalClickCount) &&
        Objects.equals(this.clicksPerLink, messageReceiptResponseDataMessage.clicksPerLink) &&
        Objects.equals(this.unsubscribed, messageReceiptResponseDataMessage.unsubscribed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, messageDeliveries, totalOpens, distinctOpens, totalClickCount, clicksPerLink, unsubscribed);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessageReceiptResponseDataMessage {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    messageDeliveries: ").append(toIndentedString(messageDeliveries)).append("\n");
    sb.append("    totalOpens: ").append(toIndentedString(totalOpens)).append("\n");
    sb.append("    distinctOpens: ").append(toIndentedString(distinctOpens)).append("\n");
    sb.append("    totalClickCount: ").append(toIndentedString(totalClickCount)).append("\n");
    sb.append("    clicksPerLink: ").append(toIndentedString(clicksPerLink)).append("\n");
    sb.append("    unsubscribed: ").append(toIndentedString(unsubscribed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `message_deliveries` to the URL query string
    if (getMessageDeliveries() != null) {
      for (int i = 0; i < getMessageDeliveries().size(); i++) {
        if (getMessageDeliveries().get(i) != null) {
          joiner.add(getMessageDeliveries().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%smessage_deliveries%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `total_opens` to the URL query string
    if (getTotalOpens() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotal_opens%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalOpens()))));
    }

    // add `distinct_opens` to the URL query string
    if (getDistinctOpens() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdistinct_opens%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDistinctOpens()))));
    }

    // add `total_click_count` to the URL query string
    if (getTotalClickCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotal_click_count%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalClickCount()))));
    }

    // add `clicks_per_link` to the URL query string
    if (getClicksPerLink() != null) {
      for (int i = 0; i < getClicksPerLink().size(); i++) {
        if (getClicksPerLink().get(i) != null) {
          joiner.add(getClicksPerLink().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sclicks_per_link%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `unsubscribed` to the URL query string
    if (getUnsubscribed() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sunsubscribed%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUnsubscribed()))));
    }

    return joiner.toString();
  }
}

