/*
 * Paubox Email API
 * Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.paubox.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.paubox.model.Message;
import java.net.URI;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.paubox.ApiClient;
/**
 * SingleSendRequestData
 */
@JsonPropertyOrder({
  SingleSendRequestData.JSON_PROPERTY_MESSAGE,
  SingleSendRequestData.JSON_PROPERTY_OVERRIDE_OPEN_TRACKING,
  SingleSendRequestData.JSON_PROPERTY_OVERRIDE_LINK_TRACKING,
  SingleSendRequestData.JSON_PROPERTY_UNSUBSCRIBE_URL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-09T17:40:55.003620791Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class SingleSendRequestData {
  public static final String JSON_PROPERTY_MESSAGE = "message";
  @javax.annotation.Nonnull
  private Message message;

  public static final String JSON_PROPERTY_OVERRIDE_OPEN_TRACKING = "override_open_tracking";
  @javax.annotation.Nullable
  private Boolean overrideOpenTracking;

  public static final String JSON_PROPERTY_OVERRIDE_LINK_TRACKING = "override_link_tracking";
  @javax.annotation.Nullable
  private Boolean overrideLinkTracking;

  public static final String JSON_PROPERTY_UNSUBSCRIBE_URL = "unsubscribe_url";
  @javax.annotation.Nullable
  private URI unsubscribeUrl;

  public SingleSendRequestData() { 
  }

  public SingleSendRequestData message(@javax.annotation.Nonnull Message message) {
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Message getMessage() {
    return message;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessage(@javax.annotation.Nonnull Message message) {
    this.message = message;
  }


  public SingleSendRequestData overrideOpenTracking(@javax.annotation.Nullable Boolean overrideOpenTracking) {
    this.overrideOpenTracking = overrideOpenTracking;
    return this;
  }

  /**
   * Set to true to enable open tracking for this message.
   * @return overrideOpenTracking
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OVERRIDE_OPEN_TRACKING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getOverrideOpenTracking() {
    return overrideOpenTracking;
  }


  @JsonProperty(value = JSON_PROPERTY_OVERRIDE_OPEN_TRACKING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOverrideOpenTracking(@javax.annotation.Nullable Boolean overrideOpenTracking) {
    this.overrideOpenTracking = overrideOpenTracking;
  }


  public SingleSendRequestData overrideLinkTracking(@javax.annotation.Nullable Boolean overrideLinkTracking) {
    this.overrideLinkTracking = overrideLinkTracking;
    return this;
  }

  /**
   * Set to true to enable click tracking for this message (up to 1000 links).
   * @return overrideLinkTracking
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OVERRIDE_LINK_TRACKING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getOverrideLinkTracking() {
    return overrideLinkTracking;
  }


  @JsonProperty(value = JSON_PROPERTY_OVERRIDE_LINK_TRACKING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOverrideLinkTracking(@javax.annotation.Nullable Boolean overrideLinkTracking) {
    this.overrideLinkTracking = overrideLinkTracking;
  }


  public SingleSendRequestData unsubscribeUrl(@javax.annotation.Nullable URI unsubscribeUrl) {
    this.unsubscribeUrl = unsubscribeUrl;
    return this;
  }

  /**
   * URL to redirect unsubscribe requests for unsubscribe tracking.
   * @return unsubscribeUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UNSUBSCRIBE_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public URI getUnsubscribeUrl() {
    return unsubscribeUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_UNSUBSCRIBE_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnsubscribeUrl(@javax.annotation.Nullable URI unsubscribeUrl) {
    this.unsubscribeUrl = unsubscribeUrl;
  }


  /**
   * Return true if this SingleSendRequest_data object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SingleSendRequestData singleSendRequestData = (SingleSendRequestData) o;
    return Objects.equals(this.message, singleSendRequestData.message) &&
        Objects.equals(this.overrideOpenTracking, singleSendRequestData.overrideOpenTracking) &&
        Objects.equals(this.overrideLinkTracking, singleSendRequestData.overrideLinkTracking) &&
        Objects.equals(this.unsubscribeUrl, singleSendRequestData.unsubscribeUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(message, overrideOpenTracking, overrideLinkTracking, unsubscribeUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SingleSendRequestData {\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    overrideOpenTracking: ").append(toIndentedString(overrideOpenTracking)).append("\n");
    sb.append("    overrideLinkTracking: ").append(toIndentedString(overrideLinkTracking)).append("\n");
    sb.append("    unsubscribeUrl: ").append(toIndentedString(unsubscribeUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `message` to the URL query string
    if (getMessage() != null) {
      joiner.add(getMessage().toUrlQueryString(prefix + "message" + suffix));
    }

    // add `override_open_tracking` to the URL query string
    if (getOverrideOpenTracking() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%soverride_open_tracking%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOverrideOpenTracking()))));
    }

    // add `override_link_tracking` to the URL query string
    if (getOverrideLinkTracking() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%soverride_link_tracking%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOverrideLinkTracking()))));
    }

    // add `unsubscribe_url` to the URL query string
    if (getUnsubscribeUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sunsubscribe_url%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUnsubscribeUrl()))));
    }

    return joiner.toString();
  }
}

