/*
 * Paubox Email API
 * Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.paubox.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.paubox.model.TemplatedMessage;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.paubox.ApiClient;
/**
 * TemplatedMessageRequestData
 */
@JsonPropertyOrder({
  TemplatedMessageRequestData.JSON_PROPERTY_TEMPLATE_NAME,
  TemplatedMessageRequestData.JSON_PROPERTY_TEMPLATE_VALUES,
  TemplatedMessageRequestData.JSON_PROPERTY_MESSAGE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-09T17:40:55.003620791Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class TemplatedMessageRequestData {
  public static final String JSON_PROPERTY_TEMPLATE_NAME = "template_name";
  @javax.annotation.Nonnull
  private String templateName;

  public static final String JSON_PROPERTY_TEMPLATE_VALUES = "template_values";
  @javax.annotation.Nonnull
  private String templateValues;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @javax.annotation.Nonnull
  private TemplatedMessage message;

  public TemplatedMessageRequestData() { 
  }

  public TemplatedMessageRequestData templateName(@javax.annotation.Nonnull String templateName) {
    this.templateName = templateName;
    return this;
  }

  /**
   * The name of the template to use (must match exactly)
   * @return templateName
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TEMPLATE_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getTemplateName() {
    return templateName;
  }


  @JsonProperty(value = JSON_PROPERTY_TEMPLATE_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTemplateName(@javax.annotation.Nonnull String templateName) {
    this.templateName = templateName;
  }


  public TemplatedMessageRequestData templateValues(@javax.annotation.Nonnull String templateValues) {
    this.templateValues = templateValues;
    return this;
  }

  /**
   * JSON-formatted string containing template variable values
   * @return templateValues
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TEMPLATE_VALUES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getTemplateValues() {
    return templateValues;
  }


  @JsonProperty(value = JSON_PROPERTY_TEMPLATE_VALUES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTemplateValues(@javax.annotation.Nonnull String templateValues) {
    this.templateValues = templateValues;
  }


  public TemplatedMessageRequestData message(@javax.annotation.Nonnull TemplatedMessage message) {
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TemplatedMessage getMessage() {
    return message;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessage(@javax.annotation.Nonnull TemplatedMessage message) {
    this.message = message;
  }


  /**
   * Return true if this TemplatedMessageRequest_data object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplatedMessageRequestData templatedMessageRequestData = (TemplatedMessageRequestData) o;
    return Objects.equals(this.templateName, templatedMessageRequestData.templateName) &&
        Objects.equals(this.templateValues, templatedMessageRequestData.templateValues) &&
        Objects.equals(this.message, templatedMessageRequestData.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(templateName, templateValues, message);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplatedMessageRequestData {\n");
    sb.append("    templateName: ").append(toIndentedString(templateName)).append("\n");
    sb.append("    templateValues: ").append(toIndentedString(templateValues)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `template_name` to the URL query string
    if (getTemplateName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stemplate_name%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTemplateName()))));
    }

    // add `template_values` to the URL query string
    if (getTemplateValues() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stemplate_values%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTemplateValues()))));
    }

    // add `message` to the URL query string
    if (getMessage() != null) {
      joiner.add(getMessage().toUrlQueryString(prefix + "message" + suffix));
    }

    return joiner.toString();
  }
}

